import { useEffect, useState } from "react";

const useGetDataRandom = (page = 1) => {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    fetch(`https://reqres.in/api/users?page=${page}`)
      .then((resp) => resp.json())
      .then((response) => {
        setUsers(response.data);
      });
  }, []);

  const getUrlImageRandom = () => {
    const idrandom = Math.floor(Math.random() * 60);
    return `https://picsum.photos/id/${idrandom === 0 ? 1 : idrandom}/300/300`;
  };

  const getUrlWallpaperRandom = () => {
    const idrandom = Math.floor(Math.random() * 60);
    return `https://picsum.photos/id/${idrandom === 0 ? 1 : idrandom}/1024/300`;
  };

  return {
    users,
    getUrlImageRandom,
    getUrlWallpaperRandom,
  };
};

export default useGetDataRandom;

// Generated by https://quicktype.io

export interface RandomUsers {
  page: number;
  per_page: number;
  total: number;
  total_pages: number;
  data: User[];
  support: Support;
}

export interface User {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  avatar: string;
}

export interface Support {
  url: string;
  text: string;
}
